version: 2.1

orbs:
  slack: circleci/slack@4.1
  kubernetes: circleci/kubernetes@1.3.1
  aws-eks: circleci/aws-eks@2.2.0
  docker: circleci/docker@2.1.4


parameters:
  workflow_id:
    type: string
    default: '${CIRCLE_WORKFLOW_ID:0:7}'

commands:
  aws-ready:
    description: Install AWS CLI
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -yy less
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            sudo pip install --upgrade pip

  

jobs:
  lint-code: 
    docker:
      - image: circleci/python:3.6.7-stretch
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            pip install -r requirements.txt
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
             
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build-project-image:
    docker:
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
          name: Upload webapp image
          command: |
            docker build --tag=capstone-project .
            docker images --all
            dockerpath=00375877633/udacity
            echo "Docker ID and Image: ${dockerpath}"
            docker login docker.io -u 00375877633 -p tuanngoc123
            docker tag capstone-project $dockerpath
            docker tag capstone-project:latest $dockerpath:latest
            docker push 00375877633/udacity:latest

  deploy-k8s:
    docker:
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      
      - run:
         name: install eksctl
          command: |  
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
      - run:
          name: build eks cluster
          command: |
           echo "create new key-pair"
           aws ec2 create-key-pair --key-name k8s-demo --query 'KeyMaterial' --output text> k8s-demo.pem
            echo "build eks cluster"
            eksctl create cluster --name k8s-demo --region us-east-1 --nodegroup-name k8s-demo --nodes 2 --node-type=t2.medium --ssh-access --ssh-public-key k8s-demo --managed
  

  
  



  # deploy-app:
  #   docker: 
  #     - image: 

  # build-infrastructure:
  #   docker:
  #     - image: circleci/python:3.6.7-stretch
  #   working_directory: ~/repo
    
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #         - v1-dependencies-{{ checksum "requirements.txt" }}
  #         # fallback to using the latest cache if no exact match is found
  #         - v1-dependencies-
  #     - aws-ready

  #     - run:
  #         name: Build Infrastructure
  #         command: |
  #           cd ./cloudformation/
  #           sh create.sh VietNguyen-Capstone-Network-<< pipeline.parameters.workflow_id >> infrastructure.yml params-infra.json

  #     - destroy-environment:
  #         when: on_fail 

  

      
workflows:
  default:
    jobs:
      - lint-code
      - build-project-image:
         requires: [lint-code]
      - deploy-k8s:
         requires: [lint-code, deploy-k8s]
     